_format_version: "1.1"

services:
  - name: orders-v1-post
    url: http://192.168.100.86:8080/message
    routes:
      - name: message
        tags:
          - orders
        methods:
          - POST
        paths:
          - "/message"
    plugins:
       - name: luizalabs-kafka
         config:
           bootstrap_servers:
             - "192.168.100.86:9092"
           timeout: 10000,
           keepalive: 60000,
           producer_request_limits_bytes_per_request: 1048576,
           producer_request_timeout: 2000,
           producer_async_flush_timeout: 1000,
           producer_request_acks: 1,
           producer_async_buffering_limits_messages_in_memory: 50000,
           producer_request_limits_messages_per_request: 200,
           producer_request_retries_max_attempts: 10,
           producer_request_retries_backoff_timeout: 100,
           producer_async: true
